### ISSUE TITLE
buddybuild feedback from kitakore@gmail.com on build #4: あー😩

### ISSUE THREAD

**Issue by henteko2** [henteko/buddybuildDemoApp#1]
Feedback from kitakore@gmail.com : あー😩

<img src="https://s3-us-west-2.amazonaws.com/buddybuild-screenshots/589ab5f095ce81010053bcdc/589ac895edb2d60100c5c936/57056c06-b264-41c8-bf13-7f475c65ecaa.jpg" width="33%" height="33%" /><table><tr><td>Created</td><td>Thu Feb 09 2017 05:04:51 GMT+0000 (UTC)</td></tr><tr><td>CFBundleShortVersion</td><td>1.0</td></tr><tr><td>CFBundleVersion</td><td>1</td></tr><tr><td>App uptime</td><td>69.19188</td></tr><tr><td>Build</td><td>4</td></tr><tr><td>Device type</td><td>iPhone 6s</td></tr><tr><td>Device name</td><td>tnj iPhone 6s</td></tr><tr><td>Screen size</td><td>375</td></tr><tr><td>Screen size</td><td>375px by 667px</td></tr><tr><td>Battery</td><td>82% Unplugged</td></tr><tr><td>Memory free</td><td>56 MB / 1807 MB</td></tr><tr><td>Memory free</td><td>16653 MB / 56367 MB</td></tr><tr><td>Network IP</td><td>192.168.1.152</td></tr></table>

**Comment by henteko** [comment]
バグですねこれは
